default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lehrstuhl_app_development
  host: localhost
  port: 5435
  #username: lehrstuhl_app
  #password:

test:
  <<: *default
  database: lehrstuhl_app_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: lehrstuhl_app_production
    username: lehrstuhl_app
    password: <%= ENV["LEHRSTUHL_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: lehrstuhl_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: lehrstuhl_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: lehrstuhl_app_production_cable
    migrations_paths: db/cable_migrate