# config/database.yml - KORRIGIERT FÜR CI/CD
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lehrstuhl_app_development
  port: 5435

test:
  <<: *default
  # KORRIGIERT: Priorisiert DATABASE_URL für CI, mit Fallback für lokale Tests.
  # In der CI wird die DATABASE_URL aus dem Workflow verwendet.
  # Lokal wird eine Standard-Postgres-Konfiguration angenommen.
  url: <%= ENV['DATABASE_URL'] %>
  database: lehrstuhl_app_test
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: lehrstuhl_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: lehrstuhl_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: lehrstuhl_app_production_cable
    migrations_paths: db/cable_migrate