# config/database.yml - RAILS-STANDARD
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lehrstuhl_app_development
  port: 5435

test:
  <<: *default
  database: lehrstuhl_app_test
  # Keine spezifischen Verbindungsparameter - lasse Rails DATABASE_URL verwenden

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: lehrstuhl_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: lehrstuhl_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: lehrstuhl_app_production_cable
    migrations_paths: db/cable_migrate