# config/database.yml - KORRIGIERTE VERSION
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5435  # Ihr lokaler Port

development:
  <<: *default
  database: lehrstuhl_app_development

# TEST-KONFIGURATION KORRIGIERT:
test:
  <<: *default
  database: lehrstuhl_app_test
  # CI/CD-spezifische Konfiguration:
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

production:
  primary: &primary_production
    <<: *default
    database: lehrstuhl_app_production
    username: lehrstuhl_app
    password: <%= ENV["LEHRSTUHL_APP_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: lehrstuhl_app_production_cache
    migrations_paths: db/cache_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_cache" } if ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
    database: lehrstuhl_app_production_queue
    migrations_paths: db/queue_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_queue" } if ENV["DATABASE_URL"] %>
  cable:
    <<: *primary_production
    database: lehrstuhl_app_production_cable
    migrations_paths: db/cable_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_cable" } if ENV["DATABASE_URL"] %>